# Generated by Django 5.0.1 on 2024-01-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0002_ingredient_rename_cook_dish_cooks_dish_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="years_for_experience",
            field=models.IntegerField(null=True),
        ),
    ]
